name: Deploy Angular Site

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install Dependencies
      run: npm install

    - name: Build Angular
      run: npm run build-github

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
          name: github-pages
          path: build/
          
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Angular Build
        uses: actions/deploy-pages@v4.0.5
        with:
          name: github-pages
